<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sd_googlemaps"
 *
 * Auto generated by Extension Builder 2017-03-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Google Maps',
	'description' => 'Embeds a google map via Maps API',
	'category' => 'plugin',
	'author' => 'David Schneiderbauer',
	'author_email' => 'david.schneiderbauer@dschneiderbauer.me',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => [
		'depends' => [
			'typo3' => '8.7.0-8.7.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
